#!/bin/bash

set -e

SOURCES_DIR=/tmp/artifacts

unzip -o $SOURCES_DIR/keycloak-server-overlay.zip -d $JBOSS_HOME

pushd $JBOSS_HOME/bin
./jboss-cli.sh --file=keycloak-install.cli
popd

chown -R jboss:root $JBOSS_HOME
chmod 0755 $JBOSS_HOME
chmod -R g+rwX $JBOSS_HOME

